### ISSUE TITLE
Threat model / Trust over IP introduction

### ISSUE THREAD

**Issue by koalie** [w3c/identity-web-impact#2]
(With caveat that I'm writing this after having read only from start to the end of section 2.2.4, and read the last use-case, and that perhaps somewhere in between lies the key to this issue. If that is the case, it means that the key needs to be brought earlier. If not, disregard the caveat and proceed to reading the below as though I had finished proof-reading the entire doc.)

If the Threat Model summarized in the last [use-case](https://w3c.github.io/identity-web-impact/#pure-digital-credentials) is of importance, I suggest it be more clearly stated.

It is introduced at the very end of [section 2.2.4](https://w3c.github.io/identity-web-impact/#opportunities-and-threats) by a Note that says "W3C is handling this issue with a [Threat Model](https://w3c.github.io/identity-web-impact/#a5)." (which is problematic as it implies endorsement; see #1 )

But then the use case merely summarizes a 35-page document that lacks a clear standing and is hosted elsewhere.

There is a discrepancy between the implied endorsement of a threat model and a use-case which summarizes what appears to be introductory slides from 2021.

If the threat model that is summarized is what the W3C Team recommends "W3C as an org" considers to handle the issue, then it needs to be framed in such a way. Furthermore, for the recommendation to have teeth, the reader has to understand the path W3C would take to handle the issue and to trust the threat model's standing.

Also "the issue" is unclear. Re-reading again section 2.2.4, it appears that "the issue" is [from the first "note" in this section] "enabling this technological innovation by being aware of the threats to Privacy, security, and Human Rights", where "this technological innovation" refers to "digital identities and credentials".

**Comment by simoneonofri** [comment]
> (With caveat that I'm writing this after having read only from start to the end of section 2.2.4, and read the last use-case, and that perhaps somewhere in between lies the key to this issue. If that is the case, it means that the key needs to be brought earlier. If not, disregard the caveat and proceed to reading the below as though I had finished proof-reading the entire doc.)

Thanks for the review and comments. I used a storytelling/discursive approach, starting with terminology and trying to introduce the various more complex concepts as the reading progresses.


> If the Threat Model summarized in the last [use-case](https://w3c.github.io/identity-web-impact/#pure-digital-credentials) is of importance, I suggest it be more clearly stated.

The purpose of the paper is: to take an overview of the identity galaxy (and in particular the decentralized model which is the one currently being implemented) and to understand the impact it has to date on both the market side but in particular on the human side (which is the one that has the most social implications) and how standards/W3C can help.
It was exploratory thinking, and the conclusions I came to are that:
- standards can help, as they have in the past, to improve the situation (see Web Authentication etc.)
- the technology stack is composite and broad, and you have to coordinate across standards and across SDOs
 - you have to pay close attention to the impact in security, privacy, and human rights in general, and the proposed method of analysis is threat modeling
 - the stakeholders with deciding together are also governments not only to have input of needs (e.g. if there is a need for a particular government - like age verification - but you don't find a technically viable solution to guarantee the various elements) but also for mitigations, the last resort is to use a legislative countermeasure. besides of course the users/citizens.
If you think this is the case, I can make this more evident in the Status and Executive Summary

> It is introduced at the very end of [section 2.2.4](https://w3c.github.io/identity-web-impact/#opportunities-and-threats) by a Note that says "W3C is handling this issue with a [Threat Model](https://w3c.github.io/identity-web-impact/#a5)." (which is problematic as it implies endorsement; see #1 )
> 
> But then the use case merely summarizes a 35-page document that lacks a clear standing and is hosted elsewhere.

The issue of doing things with respect for human rights is a recurring issue, to appreciate it it makes sense to understand both the technological/social aspect and the use case, for that's at the end, although the idea of that example was mainly to make the point that you need to collaborate among the various actors.

age verification is a much discussed and criticized case, and still no optimal solution. i'm talking about it with the community as well, and the topics are very interesting.


 
> There is a discrepancy between the implied endorsement of a threat model and a use-case which summarizes what appears to be introductory slides from 2021.

That is a slightly separate concept. The point of ToIP, which I can in case summarize with an outline, is that identity is not only technology, but also governance, particularly if we think about an end-to-end solution (which can be as utopian or dystopian as you like).
 
> If the threat model that is summarized is what the W3C Team recommends "W3C as an org" considers to handle the issue, then it needs to be framed in such a way. Furthermore, for the recommendation to have teeth, the reader has to understand the path W3C would take to handle the issue and to trust the threat model's standing.

Technically, we have an issue on the strategy where an analysis is asked for, and the Threat Model and the "how", now we are putting in the various charters the document (including FedID WG) but I confirm we don't have the mebri consensus yet (the recharter I would like to get it going next week)
 
> Also "the issue" is unclear. Re-reading again section 2.2.4, it appears that "the issue" is [from the first "note" in this section] "enabling this technological innovation by being aware of the threats to Privacy, security, and Human Rights", where "this technological innovation" refers to "digital identities and credentials".

yes, let's say the summary is, let's figure out how to make digital credentials/identities that solve more problems than they create (what) in different areas, and let's do this by collaborating between SDOs and governments.

**Comment by koalie** [comment]
I remain unsure that the note at the end of [section 2.2.4](https://w3c.github.io/identity-web-impact/#opportunities-and-threats) is appropriate. 

It would make more sense to me to point not to the last use-case of the doc, but instead to draw attention to the separate [Threat Model](https://github.com/w3c-cg/threat-modeling/blob/main/models/decentralized-identities.md) document.

**Comment by simoneonofri** [comment]
> I remain unsure that the note at the end of [section 2.2.4](https://w3c.github.io/identity-web-impact/#opportunities-and-threats) is appropriate.

+1 to remove, I'll prepare a PR

> It would make more sense to me to point not to the last use-case of the doc, but instead to draw attention to the separate [Threat Model](https://github.com/w3c-cg/threat-modeling/blob/main/models/decentralized-identities.md) document.

**Comment by simoneonofri** [comment]
> That is a slightly separate concept. The point of ToIP, which I can in case summarize with an outline, is that identity is not only technology, but also governance, particularly if we think about an end-to-end solution (which can be as utopian or dystopian as you like).

to group in one place, make ToIP figure by emphasizing that we are in layer 3 but there is the technology stack and the government part.

**Comment by simoneonofri** [comment]
Added in this PR the ToIP layers (from the DIF FAQ interpretation) https://github.com/w3c/identity-web-impact/pull/21

I am preparing another PR to update the orange box

**Comment by simoneonofri** [comment]
orange box updated https://github.com/w3c/identity-web-impact/pull/23

**Comment by simoneonofri** [comment]
thx @koalie `<3`
