### ISSUE TITLE
[architecture] "accessibility" for people with disabilities

### ISSUE THREAD

**Issue by shawna-slh** [w3c/identity-web-impact#27]
Where feasible, we prefer W3C documents to reserve "accessibility" and "accessible" as related to people with disabilities.

This use of accessibility applies to disabled people:
> They can guarantee other rights, such as the right to accessibility promoted by the Marrakesh Treaty

This use of accessibility does not:
> At this level, we find the various applications accessible to end users:

Consider re-wording to something like:
> At this level, we find the various applications available to end users:

**Comment by simoneonofri** [comment]
hi @shawna-slh thank you for the clarification. I've created a PR for this

**Comment by shawna-slh** [comment]
thank you. https://github.com/w3c/identity-web-impact/pull/28 looks just right.
