### ISSUE TITLE
Consider chain of trust and that cryptographic trust also involves verifying the issuer

### ISSUE THREAD

**Issue by verocri** [w3c/identity-web-impact#34]
In the terminology of [Cryptographic and Human trust](https://github.com/w3c/identity-web-impact/blob/49d81e5e99d9c300f4277e3815a0a0a5e0d90058/index.bs#L112), consider also the case of a chain of trust and that cryptographic trust involves not only ensuring that the credential hasn't been tampered with, but also that it was issued by an issuer you trust.

So,
> Cryptographic methods ensure that the credentials haven’t been tampered with. Human trust involves trusting the entity that issued the credential and that the issuer provided the credential to the legitimate user.

 could be modified as
"Cryptographic methods ensure that the credentials haven’t been tampered with and that they have been issued by a trusted issuer. Human trust involves trusting the entity that issued the credential or, in the case of an issuer chain, trusting the root, and that the issuer provided the credential to the legitimate user."

**Comment by simoneonofri** [comment]
https://github.com/w3c/identity-web-impact/pull/35 for your review
