### ISSUE TITLE
typo correction [HTOP to HOTP]

### ISSUE THREAD

**Issue by mashbean** [w3c/identity-web-impact#42]
https://www.w3.org/reports/identity-web-impact/#centralized-identity-model

HTOP [[RFC4226]](https://www.w3.org/reports/identity-web-impact/#biblio-rfc4226) -> HOTP [[RFC4226]](https://www.w3.org/reports/identity-web-impact/#biblio-rfc4226)

**Comment by simoneonofri** [comment]
fixed thank you @mashbean
